# Generated by Django 4.0.1 on 2024-02-07 07:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_alter_project_pid_alter_project_year'),
        ('api', '0009_alter_user_options_profile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktivitiesProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('description', models.TextField()),
                ('date_estimated', models.DateTimeField()),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('On Going', 'On Going'), ('Waiting', 'Waiting'), ('Over Due', 'Over Due')], max_length=20)),
                ('pic', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backend', to='api.profile')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_projects', to='api.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': 'Aktivities Project',
                'db_table': 'apm_aktivitiesProject',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aktivitiesproject',
            index=models.Index(fields=['-created_at'], name='apm_aktivit_created_1c443f_idx'),
        ),
    ]
