# Generated by Django 5.0.2 on 2024-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivitas_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitiesproject',
            name='tanggung_jawab',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='date_estimated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
