# Generated by Django 5.0.2 on 2024-03-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivitas_project', '0002_aktivitiesproject_tanggung_jawab_and_more'),
        ('api', '0010_remove_profile_is_active_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktivitiesproject',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='aktivitiesproject',
            name='pic',
        ),
        migrations.CreateModel(
            name='EngineerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persentase_beban_kerja', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineers', to='aktivitas_project.aktivitiesproject')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
            options={
                'unique_together': {('activity', 'engineer')},
            },
        ),
    ]
