# Generated by Django 5.0.1 on 2024-04-23 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivitas_project', '0004_aktivitiesproject_engineers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='engineers',
            field=models.ManyToManyField(related_name='activities', through='aktivitas_project.EngineerActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='pm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='engineeractivity',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
