# Generated by Django 4.0.1 on 2024-04-16 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_profile_role_alter_user_email_and_more'),
        ('aktivitas_project', '0004_aktivitiesproject_engineers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aktivitiesproject',
            name='description',
        ),
        migrations.AddField(
            model_name='aktivitiesproject',
            name='stakeholders',
            field=models.ManyToManyField(related_name='activities_as_stakeholder', through='aktivitas_project.StakeholderActivity', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='engineeractivity',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('On Going', 'On Going'), ('Waiting', 'Waiting'), ('Over Due', 'Over Due'), ('Not Started Yet', 'Not Started Yet'), ('Incompleted', 'Incompleted'), ('Chaotic', 'Chaotic')], default='Not Started Yet', max_length=20),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='engineers',
            field=models.ManyToManyField(related_name='activities', through='aktivitas_project.EngineerActivity', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('On Going', 'On Going'), ('Waiting', 'Waiting'), ('Over Due', 'Over Due'), ('Not Started Yet', 'Not Started Yet'), ('Incompleted', 'Incompleted'), ('Chaotic', 'Chaotic')], default='Chaotic', max_length=20),
        ),
        migrations.AlterField(
            model_name='engineeractivity',
            name='engineer',
            field=models.ForeignKey(limit_choices_to={'groups': 4}, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AddField(
            model_name='stakeholderactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_activities', to='aktivitas_project.aktivitiesproject'),
        ),
        migrations.AddField(
            model_name='stakeholderactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='stakeholderactivity',
            unique_together={('activity', 'user')},
        ),
    ]
