# Generated by Django 4.0.1 on 2024-04-16 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_profile_role_alter_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aktivitas_project', '0005_stakeholderactivity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='engineeractivity',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stakeholderactivity',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='engineers',
            field=models.ManyToManyField(related_name='engineer_activities', through='aktivitas_project.EngineerActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='pm',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='stakeholders',
            field=models.ManyToManyField(related_name='stakeholder_activities', through='aktivitas_project.StakeholderActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='engineeractivity',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stakeholderactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
