# Generated by Django 5.0.2 on 2024-04-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktivitas_project', '0005_alter_aktivitiesproject_engineers_and_more'),
        ('aktivitas_project', '0006_alter_engineeractivity_unique_together_and_more'),
    ]

    operations = [
    ]
