# Generated by Django 5.0.2 on 2024-04-23 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivitas_project', '0007_merge_20240423_1724'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='engineers',
            field=models.ManyToManyField(related_name='engineer_activities', through='aktivitas_project.EngineerActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aktivitiesproject',
            name='pm',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
