<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-07 06:32

import django.utils.timezone
from django.db import migrations, models
=======
# Generated by Django 4.0.1 on 2024-02-07 06:37

from django.db import migrations, models
import django.utils.timezone
>>>>>>> 16fe5fdefabe905be0941c04d5c35d348e88ca1f


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_options_alter_invoice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document_file',
            field=models.FileField(upload_to='doc/invoice/'),
        ),
    ]
