# Generated by Django 5.0.1 on 2024-04-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_name_invoice_no_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('billing to customer', 'Billing To Customer'), ('billing from subcon', 'Billing From Subcon')], default='billing to customer', max_length=50),
        ),
    ]
