# Generated by Django 5.0.2 on 2024-04-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_name_invoice_uploader'),
        ('invoice', '0005_alter_invoice_type'),
    ]

    operations = [
    ]
