# Generated by Django 5.0.2 on 2024-04-23 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_merge_20240423_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='no_invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='type',
        ),
    ]
