# Generated by Django 5.0.2 on 2024-04-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_invoice_no_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='uploader',
        ),
        migrations.AddField(
            model_name='invoice',
            name='no_invoice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('billing to customer', 'Billing To Customer'), ('billing from subcon', 'Billing From Subcon')], default='billing to customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
