# Generated by Django 5.0.2 on 2024-04-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_remove_invoice_uploader_invoice_no_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='name',
        ),
    ]
