# Generated by Django 5.0.1 on 2024-04-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoice_date'),
        ('invoice', '0009_remove_invoice_name'),
    ]

    operations = [
    ]
