# Generated by Django 5.0.1 on 2024-04-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_merge_20240426_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
