# Generated by Django 5.0.2 on 2024-03-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_profile_is_active_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
    ]
