# Generated by Django 5.0.2 on 2024-03-14 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0010_remove_profile_is_active_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_allocation', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('manual_allocation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allocated_from_projects', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocated_from_activities', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
            options={
                'verbose_name': 'Workload',
                'db_table': 'apm_workload',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='apm_workloa_created_9f1c50_idx')],
            },
        ),
    ]
