# Generated by Django 5.0.2 on 2024-03-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workload',
            name='allocated_from_activities',
        ),
        migrations.RemoveField(
            model_name='workload',
            name='allocated_from_projects',
        ),
        migrations.RemoveField(
            model_name='workload',
            name='manual_allocation',
        ),
        migrations.AddField(
            model_name='workload',
            name='activity_contribution',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workload',
            name='project_contribution',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workload',
            name='total_workload',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workload',
            name='default_allocation',
            field=models.FloatField(default=0),
        ),
    ]
