# Generated by Django 5.0.2 on 2024-03-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_remove_workload_allocated_from_activities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workload',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='workload',
            name='apm_workloa_created_9f1c50_idx',
        ),
        migrations.AlterModelTable(
            name='workload',
            table=None,
        ),
    ]
