# Generated by Django 4.0.1 on 2024-04-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0004_alter_workload_activity_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='activity_contribution',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workload',
            name='project_contribution',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workload',
            name='total_workload',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
