# Generated by Django 5.0.1 on 2024-04-25 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0005_alter_workload_activity_contribution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workload',
            options={'ordering': ['-created_at'], 'verbose_name': "Engineer's Worklod"},
        ),
        migrations.AddIndex(
            model_name='workload',
            index=models.Index(fields=['-created_at'], name='apm_workloa_created_9f1c50_idx'),
        ),
        migrations.AlterModelTable(
            name='workload',
            table='apm_workload',
        ),
    ]
