# Generated by Django 5.0.1 on 2024-04-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0006_alter_workload_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workload',
            options={'verbose_name': "Engineer's Worklod"},
        ),
        migrations.RemoveIndex(
            model_name='workload',
            name='apm_workloa_created_9f1c50_idx',
        ),
    ]
