# Generated by Django 5.0.1 on 2024-04-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0007_alter_workload_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workload',
            options={},
        ),
        migrations.AlterModelTable(
            name='workload',
            table=None,
        ),
    ]
