# Generated by Django 5.0.1 on 2024-04-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0008_alter_workload_options_alter_workload_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workload',
            table='apm_workload',
        ),
    ]
