# Generated by Django 5.0.1 on 2024-04-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_projectdocument_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='document_file',
            field=models.FileField(upload_to='doc/docfile/'),
        ),
    ]
