# Generated by Django 5.0.2 on 2024-04-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_projectdocument_document_file'),
        ('document', '0006_alter_projectdocument_uploader'),
    ]

    operations = [
    ]
