# Generated by Django 5.0.2 on 2024-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_address_alter_client_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(upload_to='client_logos/'),
        ),
    ]
