# Generated by Django 5.0.2 on 2024-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_pid_alter_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beban_proyek',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
