# Generated by Django 5.0.2 on 2024-03-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_engineerproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerproject',
            old_name='persentase_beban_kerja',
            new_name='presentase_beban_kerja',
        ),
    ]
