# Generated by Django 5.0.2 on 2024-04-14 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_persentase_beban_kerja_engineerproject_presentase_beban_kerja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='apm_project_created_6683d7_idx',
        ),
        migrations.AddField(
            model_name='engineerproject',
            name='status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Overdue', 'Overdue'), ('Waiting', 'Waiting'), ('Done', 'Done')], default='On Going', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='engineers',
            field=models.ManyToManyField(related_name='project_engagements', through='project.EngineerProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='engineerproject',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='engineerproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_projects', to='project.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='am',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Overdue', 'Overdue'), ('Waiting', 'Waiting'), ('Done', 'Done')], default='On Going', max_length=20),
        ),
    ]
