# Generated by Django 4.0.1 on 2024-04-16 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_remove_project_apm_project_created_6683d7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pm',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_pm', to=settings.AUTH_USER_MODEL),
        ),
    ]
