# Generated by Django 5.0.2 on 2024-04-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_engineerproject_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completion_percentage',
        ),
    ]
