# Generated by Django 5.0.2 on 2024-04-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_project_customer_alter_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completion_percentage',
        ),
    ]
