# Generated by Django 5.0.2 on 2024-04-24 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_project_completion_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='engineerproject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerproject',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='engineerproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_projects', to='project.project'),
        ),
        migrations.AlterField(
            model_name='engineerproject',
            name='status',
            field=models.CharField(blank=True, choices=[('On Going', 'On Going'), ('Overdue', 'Overdue'), ('Waiting', 'Waiting'), ('Done', 'Done')], default='On Going', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='engineers',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_engagements', through='project.EngineerProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('On Going', 'On Going'), ('Overdue', 'Overdue'), ('Waiting', 'Waiting'), ('Done', 'Done')], default='On Going', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
