# Generated by Django 5.0.1 on 2024-04-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_name_invoice_no_invoice_and_more'),
        ('payment', '0004_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='no_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Billing To Customer', 'Billing To Customer'), ('Billing From Subcon', 'Billing From Subcon')], default='Billing To Customer', max_length=50),
        ),
    ]
