# Generated by Django 5.0.1 on 2024-04-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_name_payment_no_invoice_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('billing to customer', 'Billing To Customer'), ('billing from subcon', 'Billing From Subcon')], default='billing to customer', max_length=50),
        ),
    ]
